In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
import plotly.express as px
warnings.filterwarnings("ignore")
%matplotlib inline

In [2]:
df = pd.read_csv('cardekho_imputated.csv',index_col=[0])

In [3]:
df.head()

,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [4]:
df.isna().sum()

car_name             0
brand                0
model                0
vehicle_age          0
km_driven            0
seller_type          0
fuel_type            0
transmission_type    0
mileage              0
engine               0
max_power            0
seats                0
selling_price        0
dtype: int64

In [5]:
df.drop(columns=['car_name','brand'],inplace=True)

In [6]:
df.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [7]:
df.describe()

,vehicle_age,km_driven,mileage,engine,max_power,seats,selling_price
count,15411.000000,1.541100e+04,15411.000000,15411.000000,15411.000000,15411.000000,1.541100e+04
mean,6.036338,5.561648e+04,19.701151,1486.057751,100.588254,5.325482,7.749711e+05
std,3.013291,5.161855e+04,4.171265,521.106696,42.972979,0.807628,8.941284e+05
min,0.000000,1.000000e+02,4.000000,793.000000,38.400000,0.000000,4.000000e+04
25%,4.000000,3.000000e+04,17.000000,1197.000000,74.000000,5.000000,3.850000e+05
50%,6.000000,5.000000e+04,19.670000,1248.000000,88.500000,5.000000,5.560000e+05
75%,8.000000,7.000000e+04,22.700000,1582.000000,117.300000,5.000000,8.250000e+05
max,29.000000,3.800000e+06,33.540000,6592.000000,626.000000,9.000000,3.950000e+07

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 15411 entries, 0 to 19543
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   model              15411 non-null  object
 1   vehicle_age        15411 non-null  int64
 2   km_driven          15411 non-null  int64
 3   seller_type        15411 non-null  object
 4   fuel_type          15411 non-null  object
 5   transmission_type  15411 non-null  object
 6   mileage            15411 non-null  float64
 7   engine             15411 non-null  int64
 8   max_power          15411 non-null  float64
 9   seats              15411 non-null  int64
 10  selling_price      15411 non-null  int64
dtypes: float64(2), int64(5), object(4)
memory usage: 1.4+ MB

In [9]:
from sklearn.model_selection import train_test_split
X = df.drop(columns='selling_price')
y = df['selling_price']

In [10]:
X.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5

In [11]:
y

0         120000
1         550000
2         215000
3         226000
4         570000
          ...
19537     250000
19540     925000
19541     425000
19542    1225000
19543    1200000
Name: selling_price, Length: 15411, dtype: int64

In [12]:
##label encoding on model
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X['model'] = le.fit_transform(X['model'])

In [13]:
X.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,7,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,54,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,118,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,7,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,38,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5

In [14]:
X['seller_type'].value_counts(),X['fuel_type'].value_counts(),X['transmission_type'].value_counts()

(seller_type
 Dealer              9539
 Individual          5699
 Trustmark Dealer     173
 Name: count, dtype: int64,
 fuel_type
 Petrol      7643
 Diesel      7419
 CNG          301
 LPG           44
 Electric       4
 Name: count, dtype: int64,
 transmission_type
 Manual       12225
 Automatic     3186
 Name: count, dtype: int64)

In [15]:
## one hot encoding because categories very less 
num_features = X.select_dtypes(exclude='object').columns
onehot_columns = ['seller_type','fuel_type','transmission_type']

from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.compose import ColumnTransformer

oh_transformer = OneHotEncoder()
scaler = StandardScaler()

preprocessor = ColumnTransformer(
    [
        ("OneHotEncoder" , oh_transformer, onehot_columns),
        ("StandardScaler", scaler, num_features)
    ],remainder='passthrough'
)

In [16]:
X = preprocessor.fit_transform(X)

In [17]:
pd.DataFrame(X).head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,-1.519714,0.983562,1.247335,-0.000276,-1.324259,-1.263352,-0.403022
1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,-0.225693,-0.343933,-0.690016,-0.192071,-0.554718,-0.432571,-0.403022
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.536377,1.647309,0.084924,-0.647583,-0.554718,-0.479113,-0.403022
3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,-1.519714,0.983562,-0.360667,0.292211,-0.936610,-0.779312,-0.403022
4,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,-0.666211,-0.012060,-0.496281,0.735736,0.022918,-0.046502,-0.403022

In [18]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y)

In [19]:
X_train.shape,X_test.shape

((11558, 17), (3853, 17))

In [21]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression,Lasso,Ridge
from sklearn.tree import DecisionTreeRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.metrics import r2_score, mean_absolute_error,mean_squared_error,root_mean_squared_error

In [22]:
def evaluate_model(true,predicted):
    mae = mean_absolute_error(true,predicted)
    mse = mean_squared_error(true,predicted)
    rmse = np.sqrt(mse)
    r2 = r2_score(true,predicted)
    return mae,mse,rmse,r2

In [23]:
models = {
    "Random Forest" : RandomForestRegressor(),
    "LinearRegression" : LinearRegression(),
    "Lasso" : Lasso(),
    "Ridge" : Ridge(),
    "KNN" : KNeighborsRegressor(),
    "Decision Tree" : DecisionTreeRegressor(),
    "Adaboost" : AdaBoostRegressor()
}

for i in range (len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train,y_train)

    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    model_train_mae, model_train_mse, model_train_rmse, model_train_r2 = evaluate_model(y_train,y_train_pred)
    model_test_mae, model_test_mse, model_test_rmse, model_test_r2 = evaluate_model(y_test,y_test_pred)

    print(list(models.keys())[i])

    print("Model performance for training dataset")
    print("mae" , model_train_mae)
    print("mse", model_train_mse)
    print("rmse", model_train_rmse)
    print("r2_score", model_train_r2)

    print("-------------------")

    print("Model performance for test dataset")
    print("mae" , model_test_mae)
    print("mse", model_test_mse)
    print("rmse", model_test_rmse)
    print("r2_score", model_test_r2)
    print('\n')

Random Forest
Model performance for training dataset
mae 40228.63788345098
mse 19490849052.896305
rmse 139609.6309460644
r2_score 0.9772377022228845
-------------------
Model performance for test dataset
mae 102687.56023578174
mse 48087887756.21102
rmse 219289.5067170589
r2_score 0.9235277435361635


LinearRegression
Model performance for training dataset
mae 275658.16946779337
mse 324296728137.0741
rmse 569470.5682799368
r2_score 0.6212715683156236
-------------------
Model performance for test dataset
mae 267728.2537635206
mse 211496186003.88736
rmse 459887.1448560911
r2_score 0.6636660221133636


Lasso
Model performance for training dataset
mae 275656.65941678535
mse 324296731613.45105
rmse 569470.5713322252
r2_score 0.6212715642557529
-------------------
Model performance for test dataset
mae 267726.9547408139
mse 211495662645.5607
rmse 459886.5758483941
r2_score 0.6636668543893076


Ridge
Model performance for training dataset
mae 275621.69766628725
mse 324297294705.258
rmse 569471.0657314013
r2_score 0.6212709066515947
-------------------
Model performance for test dataset
mae 267699.7830365734
mse 211488147203.05255
rmse 459878.4048018047
r2_score 0.6636788058987986


KNN
Model performance for training dataset
mae 91766.76328084443
mse 112768630509.71188
rmse 335810.40857857856
r2_score 0.8683036772480605
-------------------
Model performance for test dataset
mae 115291.91539060473
mse 63936025419.478325
rmse 252855.74033325468
r2_score 0.8983250801544053


Decision Tree
Model performance for training dataset
mae 4555.9785430005195
mse 339960572.76345384
rmse 18438.01976253019
r2_score 0.9996029786199299
-------------------
Model performance for test dataset
mae 124341.97811229345
mse 73593758000.27756
rmse 271281.69492296665
r2_score 0.8829667719142469


Adaboost
Model performance for training dataset
mae 435881.79568798555
mse 307624895117.6998
rmse 554639.4280230174
r2_score 0.6407416912767858
-------------------
Model performance for test dataset
mae 436911.96874801826
mse 310055478144.8019
rmse 556826.2548989602
r2_score 0.5069310974332768